# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json
PackageIdentifier: Vigolium.Vigolium
PackageVersion: '@VERSION@'
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
  - RelativeFilePath: vigolium.exe
    PortableCommandAlias: vigolium
Commands:
  - vigolium
ReleaseDate: '@RELEASE_DATE@'
Installers:
  - Architecture: x64
    InstallerUrl: '@WINDOWS_AMD64_URL@'
    InstallerSha256: '@WINDOWS_AMD64_SHA256@'
ManifestType: installer
ManifestVersion: 1.9.0
